"""add transaction_id to withdrawals

Revision ID: 5114c793219d
Revises: 8decd4964342
Create Date: 2026-08-22 15:23:41.229767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5114c793219d'
down_revision = '8decd4964342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.drop_column('transaction_id')

    # ### end Alembic commands ###
