"""add video_type to training_sessions

Revision ID: 93201eaa9591
Revises: 9b7b25b2d004
Create Date: 2026-07-23 18:49:14.216055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93201eaa9591'
down_revision = '9b7b25b2d004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_type', sa.String(length=20), nullable=False, server_default='link'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.drop_column('video_type')

    # ### end Alembic commands ###
