"""add session date/time/mode/language snapshot to masterclass_registrations

Revision ID: 951295f538f7
Revises: 9ea6724970de
Create Date: 2026-08-22 23:06:58.302471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951295f538f7'
down_revision = '9ea6724970de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('masterclass_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_date', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('session_time', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('session_mode', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('session_language', sa.String(length=60), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('masterclass_registrations', schema=None) as batch_op:
        batch_op.drop_column('session_language')
        batch_op.drop_column('session_mode')
        batch_op.drop_column('session_time')
        batch_op.drop_column('session_date')

    # ### end Alembic commands ###
