"""make achievement_id nullable and add title on achievement_requests

Revision ID: 9b7b25b2d004
Revises: 053b7b1c19bf
Create Date: 2026-07-23 16:46:18.528305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b7b25b2d004'
down_revision = '053b7b1c19bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievement_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=150), nullable=True))
        batch_op.alter_column('achievement_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievement_requests', schema=None) as batch_op:
        batch_op.alter_column('achievement_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('title')

    # ### end Alembic commands ###
