"""Add instructor fields to course

Revision ID: a1c2e5f7b9d3
Revises: 475fee85fcad
Create Date: 2026-07-16 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1c2e5f7b9d3'
down_revision = '475fee85fcad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructor_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('instructor_image_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('instructor_image_filename', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('instructor_image_filename')
        batch_op.drop_column('instructor_image_url')
        batch_op.drop_column('instructor_name')

    # ### end Alembic commands ###
