"""add market_price and gst_percent to packages

Revision ID: ac03dd825ade
Revises: cf3557294b80
Create Date: 2026-08-20 01:47:40.208331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac03dd825ade'
down_revision = 'cf3557294b80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('market_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('gst_percent', sa.Numeric(precision=5, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_column('gst_percent')
        batch_op.drop_column('market_price')

    # ### end Alembic commands ###
