"""add manager_id to users

Revision ID: cddd00d7ffde
Revises: 93201eaa9591
Create Date: 2026-07-23 20:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cddd00d7ffde'
down_revision = '93201eaa9591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['manager_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_users_manager_id'), ['manager_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_manager_id'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('manager_id')

    # ### end Alembic commands ###
