"""add instructors table and courses.instructor_id

Revision ID: ce03cc7f8abc
Revises: cddd00d7ffde
Create Date: 2026-07-24 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce03cc7f8abc'
down_revision = 'cddd00d7ffde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # `instructors` is created defensively here in case this migration runs
    # against a DB where app.create_app()'s db.create_all() hasn't already
    # created it (that call creates any model-defined table that's missing,
    # but never alters columns on tables that already exist — hence the
    # separate instructor_id column-add below is still required either way).
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'instructors' not in inspector.get_table_names():
        op.create_table(
            'instructors',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=150), nullable=False),
            sa.Column('photo_filename', sa.String(length=256), nullable=True),
            sa.Column('roles', sa.Text(), nullable=True),
            sa.Column('about', sa.Text(), nullable=True),
            sa.Column('achievements', sa.Text(), nullable=True),
            sa.Column('display_order', sa.Integer(), nullable=False),
            sa.Column('is_active', sa.Boolean(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id'),
        )

    course_cols = [c['name'] for c in inspector.get_columns('courses')]
    if 'instructor_id' not in course_cols:
        with op.batch_alter_table('courses', schema=None) as batch_op:
            batch_op.add_column(sa.Column('instructor_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key(None, 'instructors', ['instructor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('instructor_id')

    op.drop_table('instructors')

    # ### end Alembic commands ###
