"""add video to success stories

Revision ID: d929dc476bdd
Revises: aa3e66f849b5
Create Date: 2026-07-23 01:47:28.203949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd929dc476bdd'
down_revision = 'aa3e66f849b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('success_stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_filename', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('success_stories', schema=None) as batch_op:
        batch_op.drop_column('video_filename')

    # ### end Alembic commands ###
