from flask import render_template, redirect, url_for, abort
from flask_login import login_required, current_user
from app import db
from app.models import User, Commission, WalletTransaction, Order
from app.manager import manager_bp
from functools import wraps
from datetime import datetime, timezone, timedelta
from sqlalchemy import func


def manager_required(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        if not current_user.is_authenticated or current_user.role != 'manager':
            abort(403)
        return f(*args, **kwargs)
    return decorated


@manager_bp.route('/dashboard')
@login_required
@manager_required
def dashboard():
    team = User.query.filter_by(referred_by=current_user.id).order_by(User.created_at.desc()).all()

    # Team stats
    team_ids = [u.id for u in team]
    total_team = len(team)
    active_team = sum(1 for u in team if u.is_active)

    # Revenue generated by team (paid orders)
    team_revenue = 0
    if team_ids:
        team_revenue = db.session.query(func.sum(Order.amount_paid)).filter(
            Order.user_id.in_(team_ids),
            Order.payment_status == 'paid'
        ).scalar() or 0

    # Manager's own earnings
    all_time_earnings = current_user.total_earnings
    available_balance = current_user.available_balance
    pending_earnings = current_user.pending_earnings

    # Recent commissions (last 5)
    recent_commissions = current_user.commissions_received.order_by(
        Commission.created_at.desc()).limit(5).all()

    # Last 30 days earnings
    start_30 = datetime.now(timezone.utc) - timedelta(days=30)
    last_30_earnings = db.session.query(func.sum(WalletTransaction.amount)).filter(
        WalletTransaction.user_id == current_user.id,
        WalletTransaction.type == 'commission',
        WalletTransaction.status == 'completed',
        WalletTransaction.created_at >= start_30,
    ).scalar() or 0

    return render_template(
        'manager/dashboard.html',
        team=team,
        total_team=total_team,
        active_team=active_team,
        team_revenue=float(team_revenue),
        all_time_earnings=float(all_time_earnings),
        available_balance=float(available_balance),
        pending_earnings=float(pending_earnings),
        last_30_earnings=float(last_30_earnings),
        recent_commissions=recent_commissions,
    )


@manager_bp.route('/team')
@login_required
@manager_required
def team():
    members = User.query.filter_by(referred_by=current_user.id).order_by(User.created_at.desc()).all()
    return render_template('manager/team.html', members=members)


@manager_bp.route('/commissions')
@login_required
@manager_required
def commissions():
    all_commissions = current_user.commissions_received.order_by(
        Commission.created_at.desc()).all()
    return render_template('manager/commissions.html', commissions=all_commissions)
